version: "3"
services:
  mean_thug:
    container_name: mean_thug 
    image: "mean_thug"
    build:
      context: bot
      dockerfile: Dockerfile
    volumes:
      - /tmp/json:/tmp/json 
    restart: unless-stopped

  flask_api: 
    container_name: flask_api
    image: "flask_api"
    build:
      context: flask_api 
      dockerfile: flask.dev.Dockerfile
    restart: unless-stopped
    ports:
      - 5001:5001

  tda_script: 
    container_name: tda_script 
    image: "tda_script"
    build:
      context: flask_api 
      dockerfile: script.Dockerfile
    volumes: 
      - /tmp/json:/tmp/json ## memory to save wear
      - ./tokens:/app/tokens

  option_scanner_frontend:
    container_name: option_scanner_frontend 
    image: "option_scanner_frontend"
    build:
      context: frontend 
      dockerfile: dev.Dockerfile
    volumes: 
      - ./frontend:/app
