version: "3"
services:
  mean_thug:
    container_name: mean_thug 
    image: "mean_thug"
    build:
      context: bot
      dockerfile: Dockerfile
    volumes:
      - /tmp/json:/tmp/json 
    restart: unless-stopped

  flask_api: 
    container_name: flask_api
    image: "flask_api"
    build:
      context: flask_api 
      dockerfile: flask.Dockerfile
    ports:
      - 5000:5000
    volumes: 
      - /tmp/json:/tmp/json ## memory to save wear
    restart: unless-stopped

  tda_script: 
    container_name: tda_script 
    image: "tda_script"
    build:
      context: flask_api 
      dockerfile: script.Dockerfile
    volumes: 
      - /tmp/json:/tmp/json ## memory to save wear
      - ./tokens:/app/tokens

  ipo_scrape:
    container_name: ipo_scrape 
    image: "ipo_scrape"
    build:
      context: flask_api
      dockerfile: ipo_scrape.Dockerfile
    volumes:
      - /tmp/json:/tmp/json 