version: "2"
services:
  mean_thug:
    container_name: mean_thug 
    image: "mean_thug"
    build:
      context: bot
      dockerfile: Dockerfile
    volumes:
      - /tmp/json:/tmp/json
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

      
    restart: unless-stopped

  flask_api: 
    container_name: flask_api
    image: "flask_api"
    build:
      context: flask_api 
      dockerfile: flask.Dockerfile
    ports:
      - 5000:5000
    volumes: 
      - /tmp/json:/tmp/json ## memory to save wear
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

    restart: unless-stopped

  tda_script: 
    container_name: tda_script 
    image: "tda_script"
    build:
      context: flask_api 
      dockerfile: tda_script.Dockerfile
    volumes: 
      - /tmp/json:/tmp/json ## memory to save wear
      - /tmp/data:/tmp/data
      
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  6h_scripts:
    container_name: 6h_scripts 
    image: "6h_scripts"
    build:
      context: flask_api 
      dockerfile: 6h_scripts.Dockerfile
    volumes:
      - /tmp/json:/tmp/json 
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  get_earnings_script:
    container_name: get_earnings_script
    image: "get_earnings_script"
    build:
      context: flask_api
      dockerfile: get_earnings_script.Dockerfile
    volumes:
      - /tmp/json:/tmp/json  
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"



  myfxbook_script:
    container_name: myfxbook_script
    image: "myfxbook_script"
    build:
      context: bot
      dockerfile: myfxbook_script.Dockerfile
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"