version: "3"
services:
  calliebot_discord:
    container_name: calliebot_discord
    image: "calliebot_discord"
    build:
      context: .
      dockerfile: discordBot.Dockerfile
    volumes:
      - /mnt/ramdisk/calliebot:/app
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  flask_gunicorn:
    container_name: flask_gunicorn
    image: "flask_gunicorn"
    build:
      context: . 
      dockerfile: flask_gunicorn.Dockerfile
    volumes:
      - /mnt/ramdisk/calliebot:/app
    ports:
      - 5000:5000
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"